#ifndef __GUIMyFrameMyFrame1__
#define __GUIMyFrameMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/
#include "CImg.h"
#include "MyVeryOwnClass.h"
#include <wx/dcbuffer.h>
#include <wx/window.h>
#include <string>
#include <wx/wx.h>
#include "wx/wxprec.h"
#include "FreeImage.h"
#include <wx/richtext/richtextctrl.h>

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrameMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.
	void m_button1OnButtonClick (wxCommandEvent &event) override;

	void m_button2OnButtonClick (wxCommandEvent &event) override;

	void m_erode (wxCommandEvent &event) override;

	void m_animacja (wxCommandEvent &event) override;

	void MyFrame1OnUpdateUI (wxUpdateUIEvent &event) override;


public:
	/** Constructor */
	explicit GUIMyFrameMyFrame1 (wxWindow *parent);

	wxImage *m_image = new wxImage ();

	~GUIMyFrameMyFrame1 () override
	{
		delete m_image;
	}

	void refresh (wxClientDC &dc);
	//// end generated class members

};

#endif // __GUIMyFrameMyFrame1__
