#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "vecmat.h"
//// end generated include

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
protected:
	// Handlers for MyFrame1 events.
	void WxPanel_Repaint (wxUpdateUIEvent &event) override;

	void m_button_load_geometry_click (wxCommandEvent &event) override;

	void Scrolls_Updated (wxScrollEvent &event) override;

public:
	/** Constructor */
	GUIMyFrame1 (wxWindow *parent);
	//// end generated class members

	Matrix4 center ();

	Matrix4 rotate_x (double rotation);

	Matrix4 rotate_y (double rotation);

	Matrix4 rotate_z (double rotation);

	Matrix4 scale (double x, double y, double z);

	Matrix4 translate (double x, double y, double z);

	void Repaint ();


};

#endif // __GUIMyFrame1__
